strA = '''>NC_000012.12:c102481839-102395874 Homo sapiens chromosome 12, GRCh38.p14 Primary Assembly
AAGCAGAACTGTGTTTTCAGTTGATGTGTCAGTCCCCTGAGAGTCATGTGGAAAAAAAAAAAAAGAAAAA
ATTCAAGGTCCAGGTTATTTCCACCACTCCTGGGAAACCAGGCCTGGAGAGCTCTCTAGGGAAAGAGGTA
TGTCTGCTCTGGGCTTTTGCAACCTTATTTTATAATTCACTTTCTTATCTACTGCTTCACAAAACCAAAG
GGAAATAGGTACAAACTGTATCGACAAAAGATCAGAACTGAATTCTCAATGGCAAAGGCAAGTGTACATT
ATAAATAGCAAAACAGCTGGCTTGGACCATGTTGCCGGCCAGTCACCCAGTTGAGGGATTTGAATGACAT
CATAACCCTCGAGAGGGTATTGCTAGCCAGCTGGTGTTATTTAGAATACACAAAAATCAGAGAAAGAAAA
CACACTCTGGCACACAGACTCCCTCTGTCATACACACACACACACACACACACACACACACACACACACA'''
listA = strA.splitlines(); #print(listA)
print(len(listA))
print(min(listA), min(listA)[0], ord(min(listA)[0]))
print(max(listA), max(listA)[0], ord(max(listA)[0]))
